name: php-cs-fixer
on: [ push, pull_request ]

jobs:
  php-cs-fixer:
    runs-on: [self-hosted, linux, x64]
    name: Run PHP CS
    steps:
      - name: Run PHPCS
        run: |
          phpcs --standard=PSR12 index.php
