name: php-cs-fixer

env:
  PR_NUMBER: "${{ github.event.number }}"
  SOURCE_BRANCH: "$GITHUB_HEAD_REF"
  FIXER_BRANCH: "auto-fixed/$GITHUB_HEAD_REF"
  TITLE: "Apply fixes from PHP-CS-Fixer"
  DESCRIPTION: "This merge request applies PHP code style fixes from an analysis carried out through GitHub Actions."

on: [ push, pull_request ]

jobs:
  php-cs-fixer:
    if: github.event_name == 'pull_request' && ! startsWith(github.ref, 'refs/heads/auto-fixed/')
    runs-on: [self-hosted, linux, x64]

    name: Run PHP CS Fixer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Run PHPCS
        run: |
          phpcs *.php